services:

  postgres:
    container_name: postgres
    image: postgres:15.4
    networks:
      default:
        aliases:
          - postgresql.db.service
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
  
  redis:
    container_name: redis
    image: redis:7.2
    networks:
      default:
        aliases:
          - redis.cache.service
    volumes:
      - redis_cache:/data

  django:
    container_name: django
    build:
      context: ./
      dockerfile: docker/mail/Dockerfile
    networks:
      default:
        aliases:
          - django.service
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    expose:
      - 8000
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/

  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: ./docker/admin/Dockerfile
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/


volumes:
  postgres_volume:
  static_volume:
  media_volume:
  redis_cache: