# Generated by Django 5.1.2 on 2024-10-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль пользователя')),
                ('server', models.CharField(choices=[('imap.gmail.com', 'Google'), ('imap.mail.ru', 'Mail.ru'), ('imap.yandex.ru', 'Yandex')], max_length=14, verbose_name='IMAP Сервер')),
            ],
        ),
    ]
