# Generated by Django 5.1.2 on 2024-10-31 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='mail.server')),
            ],
        ),
    ]
