# Generated by Django 5.1.2 on 2024-10-31 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_id', models.IntegerField(verbose_name='ID Сообщения на сервере')),
                ('sender', models.TextField(verbose_name='Отправитель')),
                ('theme', models.TextField(blank=True, default=None, null=True, verbose_name='Тема сообщения')),
                ('sending_date', models.DateTimeField(verbose_name='Дата отправки')),
                ('receiving_date', models.DateTimeField(verbose_name='Дата получения')),
                ('text', models.TextField(blank=True, default=None, null=True, verbose_name='Текст сообщения')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='mail.folder')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail.mail')),
            ],
        ),
    ]
