# Generated by Django 5.1.2 on 2024-10-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_mail_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='receiving_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='sending_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата отправки'),
        ),
    ]
